<div class="banner-main">
<?php

echo $block->getLayout()

           ->createBlock('Magento\Cms\Block\Block')

           ->setBlockId('outdoor-dining')

           ->toHtml();

?>


</div>

<script>
    require(['jquery', 'jquery/ui', 'slick'], function($) {
    $(document).ready(function() {
        $('.banner-main').slick({
       dots: false,
       infinite: true,
       speed: 300,
       arrows: false,
       slidesToShow: 1,
       slidesToScroll: 1
    });

    });
});

</script>